### ISSUE TITLE
工单服务项目添加，有点小改动

### ISSUE THREAD

**Issue by wushuaiping** [GoodWeking/joessemApk#2]
点击添加按钮，下面直接出现新的一行，不用再去选择服务项目了，然后列表的服务项目改成了可输入的。

**Comment by wushuaiping** [comment]
![image](https://user-images.githubusercontent.com/26813459/223353815-2f11ca0b-c55e-4e9d-8e87-3a268206c24d.png)

**Comment by GoodWeking** [comment]
已完成
