### ISSUE TITLE
工单列表，tab栏的状态筛选，和后端的状态保持一致

### ISSUE THREAD

**Issue by wushuaiping** [GoodWeking/joessemApk#3]
![image](https://user-images.githubusercontent.com/26813459/223354681-2e62c3ce-dce4-4193-81ea-713ee7be9d0a.png)
- 后台返回的参数
![image](https://user-images.githubusercontent.com/26813459/223354740-5844ec37-5372-4037-9e4f-c1f47abefc9f.png)

**Comment by GoodWeking** [comment]
已处理
