### ISSUE TITLE
个人中心 统计数量需要展示出来

### ISSUE THREAD

**Issue by wushuaiping** [GoodWeking/joessemApk#6]
![image](https://user-images.githubusercontent.com/26813459/224952057-7e9ffa92-d119-461d-9190-ffa2dd3e34e7.png)

**Comment by GoodWeking** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/106650697/225257713-ccbacc16-32d5-4425-9e3c-7af1e18fd4c0.png">
是接口返回0
